var mydate=new Date()
var timeOfDay=mydate.getHours()

if (timeOfDay>=6 && timeOfDay<12)
document.write('Good morning')
else if (timeOfDay>=12 && timeOfDay<19)
document.write('Good afternoon')
else if (timeOfDay>=19 && timeOfDay<24)
document.write('Good evening')
else if (timeOfDay<6 || timeOfDay>=24)
document.write('Hi Night Owl')
